services:
  go:
    container_name: go_api
    image: 420.crypto.test/go
    build:
      context: ./
      dockerfile: ./infrastructure/docker/Dockerfile
    restart: on-failure
    networks:
      - internal
      - 420cry.test
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    container_name: api_web
    image: 420.crypto.test/nginx:go
    depends_on:
      - go
    restart: on-failure
    networks:
      - internal
      - 420cry.test
    volumes:
      - .:/app

networks:
  internal:
    name: api_internal
  420cry.test:
    name: 420cry.test
    external: true