services:
  go:
    container_name: 420cry_api
    image: 420cry.test/go
    build:
      context: ./
      dockerfile: ./infrastructure/docker/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - 420cry.test

networks:
  420cry.test:
    name: 420cry.test
    external: true